api:
  host: localhost
  port: 8000
  debug: false
queue:
  max_size: 1000
  batch_size: 10
worker:
  num_workers: 4
  poll_interval: 1
retry:
  max_attempts: 3
  initial_delay: 1
  max_delay: 300
logging:
  level: INFO
  file_path: app.log