version: '3.8'

services:
  # Ray head node service
  ray-head:
    image: rayproject/ray:2.42.1
    container_name: ray-head
    ports:
      - "8265:8265"   # Ray dashboard
      - "6379:6379"   # Ray GCS server
      - "10001:10001" # Ray client server
      - "8000:8000"   # FastAPI application
    volumes:
      - ../:/queue-engine
    command: >
      bash -c "
        ray start --head --port=6379 --dashboard-host=0.0.0.0 --dashboard-port=8265 --block &
        cd /queue-engine &&
        pip install -r requirements.txt &&
        python -m src.main
      "
    environment:
      - RAY_ADDRESS=localhost:6379
    networks:
      - ray-network
    healthcheck:
      test: ["CMD", "ray", "status"]
      interval: 10s
      timeout: 10s
      retries: 5

  # Ray worker nodes
  ray-worker-1:
    image: rayproject/ray:2.42.1
    container_name: ray-worker-1
    depends_on:
      ray-head:
        condition: service_healthy
    volumes:
      - ../:/queue-engine
    command: >
      bash -c "
        ray start --address=ray-head:6379 --block
      "
    networks:
      - ray-network

  ray-worker-2:
    image: rayproject/ray:2.42.1
    container_name: ray-worker-2
    depends_on:
      ray-head:
        condition: service_healthy
    volumes:
      - ../:/queue-engine
    command: >
      bash -c "
        ray start --address=ray-head:6379 --block
      "
    networks:
      - ray-network

  # Monitoring service with Prometheus
  prometheus:
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus:/etc/prometheus
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
    networks:
      - ray-network

  # Grafana for visualization
  grafana:
    image: grafana/grafana:10.1.0
    container_name: grafana
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_USERS_ALLOW_SIGN_UP=false
    networks:
      - ray-network
    depends_on:
      - prometheus

networks:
  ray-network:
    driver: bridge

volumes:
  prometheus_data:
  grafana_data: